---
- name: check virtualization type
  assert:
    msg: "virtualization is not kvm guest"
    that:
      - "ansible_virtualization_role == 'guest'"
      - "ansible_virtualization_type == 'VMware'"
