---
# tasks file for hudecof.open-vm-tools

- name: Set os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_distribution }}.yml"
    - "os-default.yml"
  tags:
    - always

- name: Include packages tasks
  ansible.builtin.include_tasks:
    file: check-common.yml
    apply:
      tags:
        - open-vm-tools
        - open-vm-tools:check
  when: open_vm_tools_supported
  tags:
    - always

- name: Include packages tasks
  ansible.builtin.include_tasks:
    file: packages-{{ ansible_os_family }}.yml
    apply:
      tags:
        - open-vm-tools
        - open-vm-tools:packages
  when: open_vm_tools_supported
  tags:
    - always

- name: Include service tasks
  ansible.builtin.include_tasks:
    file: service-common.yml
    apply:
      tags:
        - open-vm-tools
        - open-vm-tools:service
  when: open_vm_tools_supported
  tags:
    - always
