---
# tasks file for hudecof.open-vm-tools

- name: Include packages tasks
  ansible.builtin.include_tasks: check-common.yml
  tags:
    - open-vm-tools
    - open-vm-tools:check

- name: Set os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_distribution }}.yml"
  tags:
    - always

- name: Include packages tasks
  ansible.builtin.include_tasks: packages-{{ ansible_os_family }}.yml
  tags:
    - open-vm-tools
    - open-vm-tools:packages

- name: Include service tasks
  ansible.builtin.include_tasks: service-common.yml
  tags:
    - open-vm-tools
    - open-vm-tools:service
