---
- name: "Check packages (redhat)"
  ansible.builtin.yum:
    pkg: "{{ package.name }}"
    state: "{{ package.state }}"
  with_items: "{{ open_vm_tools_packages }}"
  loop_control:
    loop_var: package
