---
- name: "Enable service for VmWare tools"
  ansible.builtin.service:
    name: "{{ open_vm_tools_service }}"
    enabled: "{{ open_vm_tools_service_enabled }}"
    state: "{{ open_vm_tools_service_state }}"
